"""
Code for storing data with Prefect.
"""
from pathlib import Path

from prefect_aws import S3Bucket

from prefect_.loggers import get_prefect_or_default_logger


def create_bucket_with_resolved_subpath(
    key: str,
    __bucket: S3Bucket,
) -> S3Bucket:
    """Creates a child `S3Bucket` of `bucket` whose `bucket_folder` is within
    `bucket.bucket_folder`.
    :param key:     Child path from `bucket.bucket_folder`
    :param bucket:  `S3Bucket` to create a child from
    :return:        `S3Bucket` whose `bucket_folder` is\
        `bucket.bucket_folder`/`key`
    ## Example
    ```py
    bucket: S3Bucket = ...
    # bucket.bucket_folder == "base_folder/"
    child_bucket = create_bucket_with_resolved_subpath("child_folder", bucket)
    # child_bucket.bucket_folder == "base_folder/child_folder/"
    ```
    """
    new_bucket_folder: Path | str = __bucket._resolve_path(key)

    # While prefect_aws.S3Bucket is moving to the `bucket_folder` attribute,
    # LocalFileSystem still uses `basepath`
    update = {}
    if hasattr(__bucket, "bucket_folder"):
        update["bucket_folder"] = new_bucket_folder
    elif hasattr(__bucket, "basepath"):
        update["basepath"] = new_bucket_folder
    else:
        raise TypeError(f"{__bucket!s} does not have attribute 'basepath'")
    return __bucket.copy(update=update)


def create_child_bucket(
    key: str, suffix: str, parent: S3Bucket
) -> S3Bucket:
    """Creates a child bucket with a derived _block_document_name.

    :param key:         Child bucket's subpath
    :param suffix:      Suffix to append to the parent's document name.\
        Creates
    :param parent:    Bucket to create a child from, defaults to global\
        `bucket`
    :return:            Returns the child


    """
    child = create_bucket_with_resolved_subpath(key, parent)
    child = child.copy(
        # https://github.com/PrefectHQ/prefect/blob/main/src/prefect/results.py
        # Exclude the _block_document_id, this can be generated by the
        # ResultFactory and it will be saved anonymously there
        exclude={"_block_document_id"},
        update={
            "_block_document_name": parent._block_document_name + suffix,
            "_is_anonymous": True,
        },
    )
    return child


def task_persistence_subfolder(
    bucket: S3Bucket,
    key: str | None = None,
    suffix: str | None = None,
):
    """Decorator to set the `task.result_storage` attribute to a subfolder of
    `bucket`. `key` will be relative to the existing `bucket.bucket_folder`.
    If no key is given, then `task.fn.__name__` will be used as the subfolder.
    NOTE This method does not alter the `result_serializer` or
    `persist_result` attributes. `**kwds` are passed to
    `create_bucket_with_resolved_subpath`.

    :param bucket:  `S3Bucket` to create a child folder for
    :param key:     Folder to resolve `bucket_folder` to
    :param suffix:  Suffix to append to anonymous block name, defaults to\
        `task.fn.__name__`
    :return:        Task whose `result_storage` outputs to a subfolder
    ## Examples
    ```py
    bucket: S3Bucket = ...
    # bucket.bucket_folder == "base_folder/"
    @task_persistence_subfolder(bucket)
    @task(result_serializer=PickleSerializer, persist_result=True)
    def persisted_task(data: dict) -> dict:
        '''A task whose return value is persisted in a subfolder of `bucket`.
        '''
        ...
    # Results will be persisted to "base_folder/persisted_task/"
    @task_persistence_subfolder(bucket, key="AlternativePersistedTask")
    @task(result_serializer=PickleSerializer, persist_result=True)
    def second_persisted_task(data: dict) -> dict:
        '''A task whose return value is persisted in a subfolder of `bucket`.
        '''
        ...
    # Results will be persisted to "base_folder/persisted_task/"
    ```
    """

    def decorator(task):
        """Decorates the task to assign a new `task.result_storage`."""
        logger = get_prefect_or_default_logger()
        task.result_storage = create_child_bucket(
            key or task.fn.__name__,
            suffix or "-" + task.fn.__name__.replace("_", "-"),
            parent=bucket,
        )
        logger.debug(
            "Task %s is being persisted to storage %s",
            task,
            task.result_storage,
        )
        return task

    return decorator
